// https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
// https://www.jetbrains.com/help/idea/http-response-handling-examples.html#checking-response-headers-body

### Suche mit vorhandenem Namen
GET {{baseUrl}}/rest?name=Phi
Accept: application/hal+json

### Suche mit nicht-vorhandenem Namen
GET {{baseUrl}}/rest?name=Nichtvorhanden
Accept: application/hal+json


### Suche Namen mit Praefix
GET {{baseUrl}}/rest/name/A
Accept: application/hal+json

### Suche mit vorhandenem id
GET {{baseUrl}}/rest/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
